---
title: "Exploring alternative Bayesian estimates of low- and no-effect concentration thresholds"
author: "Rebecca Fisher"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, cache = TRUE)

require(jagsNEC)
require(tidyverse)
library(ggplot2)
library(ggthemes) 
library(ggnewscale)
library(kableExtra)
library(flextable)
library(officer)
library(ggtext)
library(ggh4x)
library(scales)
library(cowplot)
library(gridGraphics)
library(multcomp)
library(glmmTMB)
source('functions.R')

options(timeout = max(3000, getOption("timeout")))

# To download and extract using R.
# temp <- tempfile()
# download.file("https://data.aims.gov.au/data-download/49a297f2-48f5-4770-bccf-a21be78ec813/All-R-files_NSEC_IEAM.zip",temp)
# load(unz(temp, "binomial_sim_results.RData"))
# load(unz(temp, "fitted_binom_examples.RData")) #simulation results
# load(unz(temp, "cu_pred_vals.RData")) #case study 1
# load(unz(temp, "caste_study_results.RData")) #case study 2
# load(unz(temp, "Case_study_condensate_for_plotting.RData")) #case study 2
# unlink(temp)

load(file = "binomial_sim_results.RData") #simulation results
load(file = "fitted_binom_examples.RData") #simulation results
load(file = "cu_pred_vals.RData") #case study 1
load(file = "caste_study_results.RData") #case study 2
load(file = "Case_study_condensate_for_plotting.RData") #case study 2

x.range <- c(0.1, 10)
x.vec <- seq(x.range[1], x.range[2], length=50)

true.vals <- do.call("rbind", true.endpoints) %>%
  mutate(estimate=gsub("C1", "C01", endpoint),
         estimate=gsub("C5", "C05", endpoint),
         estimate=gsub("C010", "C10", endpoint)) |> 
  mutate(scenarios_f = as_factor(scenarios), 
          scenarios_f = fct_relevel(scenarios_f,"NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2")) 

true.vals.2<-true.vals %>% mutate(scenarios_f = as_factor(scenarios), 
          scenarios_f = fct_relevel(scenarios_f,"NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2"), 
          endpoint=fct_relevel(endpoint, "NEC", "EC1", "EC5", "EC10")) %>% 
    mutate(y_2 = if_else(str_detect(scenarios, "NEC")&endpoint %in% c("EC1", "EC5", "EC10"),  NA, y))

dat <- all.sim.out %>%
  mutate(est.NEC=NEC_X50.,
         est.NSEC=NSEC01.ECxsigmoidal_X50.,
         est.N.S.EC=NSEC01.ECxsigmoidal_X50.*ECxsigmoidal + NEC_X50.*NEC3param,         
         est.EC10=ECx10.ECxsigmoidal_X50.*ECxsigmoidal + ECx10.NEC3param_X50.*NEC3param,
         est.EC05=ECx05.ECxsigmoidal_X50.*ECxsigmoidal + ECx05.NEC3param_X50.*NEC3param,
         est.EC01=ECx01.ECxsigmoidal_X50.*ECxsigmoidal + ECx01.NEC3param_X50.*NEC3param,
         est.NEC.up=NEC_X97.5.,
         est.NSEC.up=NSEC01.ECxsigmoidal_X97.5.*ECxsigmoidal + NSEC01.NEC3param_X97.5.*NEC3param,
         est.EC10.up=ECx10.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx10.NEC3param_X97.5.*NEC3param,
         est.EC05.up=ECx05.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx05.NEC3param_X97.5.*NEC3param,
         est.EC01.up=ECx01.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx01.NEC3param_X97.5.*NEC3param,     
         est.NEC.lw=NEC_X2.5.,
         est.NSEC.lw=NSEC01.ECxsigmoidal_X2.5.*ECxsigmoidal + NSEC01.NEC3param_X2.5.*NEC3param,
         est.EC10.lw=ECx10.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx10.NEC3param_X2.5.*NEC3param,
         est.EC05.lw=ECx05.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx05.NEC3param_X2.5.*NEC3param,
         est.EC01.lw=ECx01.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx01.NEC3param_X2.5.*NEC3param,
         label=paste(n, " reps (", trials, " trials)", sep=""))  %>% 
  mutate(label=as.factor(label), 
         scenarios_f = as_factor(scenarios), 
         label = fct_relevel(label, 
             "5 reps (10 trials)", "5 reps (20 trials)", "10 reps (10 trials)", "10 reps (20 trials)"))
# check treatments

nsec_ecx_vals <- ((0.9-sapply(1:nrow(dat),  FUN = function(i){  
  param_vec <- dat[i, c("top", "beta", "NEC", "d")]
  x_val <- dat[i, "est.NSEC"]
  unlist(estECX_vals(x=x_val, params = param_vec))  
})) / 0.9) *100

n.s.ec_ecx_vals <- ((0.9-sapply(1:nrow(dat),  FUN = function(i){  
  param_vec <- dat[i, c("top", "beta", "NEC", "d")]
  x_val <- dat[i, "est.N.S.EC"]
  unlist(estECX_vals(x=x_val, params = param_vec))  
})) / 0.9) *100

ec1_ecx_vals <- ((0.9-sapply(1:nrow(dat),  FUN = function(i){  
  param_vec <- dat[i, c("top", "beta", "NEC", "d")]
  x_val <- dat[i, "est.EC01"]
  unlist(estECX_vals(x=x_val, params = param_vec))  
})) / 0.9) *100

ec5_ecx_vals <- ((0.9-sapply(1:nrow(dat),  FUN = function(i){  
  param_vec <- dat[i, c("top", "beta", "NEC", "d")]
  x_val <- dat[i, "est.EC05"]
  unlist(estECX_vals(x=x_val, params = param_vec))  
})) / 0.9) *100

ec10_ecx_vals <- ((0.9-sapply(1:nrow(dat),  FUN = function(i){  
  param_vec <- dat[i, c("top", "beta", "NEC", "d")]
  x_val <- dat[i, "est.EC10"]
  unlist(estECX_vals(x=x_val, params = param_vec))  
})) / 0.9) *100

nec_ecx_vals <- ((0.9-sapply(1:nrow(dat),  FUN = function(i){  
  param_vec <- dat[i, c("top", "beta", "NEC", "d")]
  x_val <- dat[i, "est.NEC"]
  unlist(estECX_vals(x=x_val, params = param_vec))  
})) / 0.9) *100

dat$nsec_ecx_vals <- nsec_ecx_vals
dat$n.s.ec_ecx_vals <- n.s.ec_ecx_vals
dat$ec1_ecx_vals <- ec1_ecx_vals
dat$ec5_ecx_vals <- ec5_ecx_vals
dat$ec10_ecx_vals <- ec10_ecx_vals
dat$nec_ecx_vals <- nec_ecx_vals

true_ec_dat <-expand.grid(
   scenarios=unique(dat$scenarios), endpoint = c("EC1", "EC5", "EC10")) |> 
  mutate(y=as.numeric(gsub("EC", "", endpoint)))  |> 
  mutate(scenarios_f = as_factor(scenarios), 
          scenarios_f = fct_relevel(scenarios_f,"NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2")) 

true_all_dat <-expand.grid(
   scenarios=unique(dat$scenarios),
   endpoint = c("EC01", "EC05", "EC10", "NEC", "NSEC", "N(S)EC")) |> 
  mutate(y=as.numeric(gsub("EC", "", endpoint)))  |> 
  mutate(y=ifelse(is.na(y), 0, y))  |> 
  mutate(scenarios_f = as_factor(scenarios), 
          scenarios_f = fct_relevel(scenarios_f,"NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2")) 

```

## Figure 1

```{r sims}
sim_dat_ret <- do.call("rbind", strsplit(names(sim.dat.binom), split = "_")) |> 
  data.frame() |> 
  mutate(key = names(sim.dat.binom),
         n.treatments = X1,
         n.replicates = X2,
         n.trials = X4,
         scenario = X5) |> 
  dplyr::select(key, n.treatments, n.replicates, n.trials, scenario)

all_sim_examples_dat<- lapply(sim_dat_ret$key, FUN = function(x){
  data.frame(fitted.binom[[x]]$mod.fits$ECxsigmoidal$mod.dat)
})
names(all_sim_examples_dat) <- sim_dat_ret$key

all_sim_examples_dat <- all_sim_examples_dat |> bind_rows(.id = "key") |> 
  left_join(sim_dat_ret) |> 
  mutate(label=factor(paste(n.replicates, " reps (", n.trials, " trials)", sep="")))  %>% 
  filter(label=="5 reps (10 trials)" | label=="10 reps (20 trials)") %>%
  mutate(Model = ifelse(grepl("NEC", scenario), "NEC", "Sigmoidal")) |> 
  mutate(label = fct_relevel(label, 
             "5 reps (10 trials)", "5 reps (20 trials)", "10 reps (10 trials)", "10 reps (20 trials)"))

scenarios <- names(scenarios.list)
scenarios.dat <- do.call("rbind", scenarios.list) %>%
  data.frame() %>%
  rownames_to_column(var = "scenarios")

x.range <- c(0.1, 10)
x.vec8 <- seq(x.range[1], x.range[2], length=8)
x.vec12 <- seq(x.range[1], x.range[2], length=12)

p1 <- ~{
  par(bty="n", cex=0.75, oma=c(0,0,0,0))
  plot(x.vec, ECxsigmoidal(x=x.vec, top=0.9, beta=0.01, d=2), ylim = c(0,1), 
       pch=NA,   ylab="", xlab="")
  arrows(x0=scenarios.dat$NEC[2], y0=0.2, x1=scenarios.dat$NEC[2], y1=0,
         col = "#41b6c4", lwd=3, length = 0.1)
  arrows(x0=scenarios.dat$NEC[4], y0=0.2, x1=scenarios.dat$NEC[4], y1=0,
         col = "#41b6c4", lwd=3, length = 0.1)
  abline(h=0.9*0.9, col = "#91003f", lwd=1, lty=2)
  text(x = na.omit(scenarios.dat$NEC), y = 0.2, labels = c("NEC 1", "NEC 2"), col="#41b6c4", pos=3)
  text(x = 1, y = 0.9*0.9, labels = "10% effect", col="#91003f", pos=1)
  axis(side = 1, labels = rep("", length(x.vec12)), at = x.vec12, col.ticks = "#2D6480", lwd.ticks=3)
  axis(side = 1, labels = rep("", length(x.vec8)), at = x.vec8, col.ticks = "#B3AE36", lwd.ticks=3)

  lines(x.vec, do.call(ECxsigmoidal, c(list(x.vec), as.list(na.omit(scenarios.list$`Sigmoidal 1`)))), col=1, lty=1)
  lines(x.vec, do.call(ECxsigmoidal, c(list(x.vec), as.list(na.omit(scenarios.list$`Sigmoidal 2`)))), col=1, lty=2)

  lines(x.vec, do.call(NEC3param, c(list(x.vec), as.list(na.omit(scenarios.list$`NEC 1`)))), col="#41b6c4", lty=1)
  lines(x.vec, do.call(NEC3param, c(list(x.vec), as.list(na.omit(scenarios.list$`NEC 2`)))), col="#41b6c4", lty=2)

  legend("right", legend=scenarios,
         lty=c(1,1,2,2), 
         col=c(1,"#41b6c4",1,"#41b6c4"), 
         bty = "n")
  legend("top", legend=c("8 treatments", "12 treatments"), 
         col = c("#B3AE36", "#2D6480"),
         lty=1, bty="n", lwd=3, ncol = 2, pch=16, cex = 1.25)
  mtext(side = 1, text = "Concentration (x)", line = 2, cex=0.9)
  mtext(side = 2, text = "Response (y)", line = 2, cex=0.9)
  }

p2 <- all_sim_examples_dat |> 
  ggplot(aes(x=x, y=y/trials, col = n.treatments)) + 
  geom_jitter(alpha=0.5) +
  facet_grid(label ~ scenario) +
  ylab("Response (y)") +
  xlab("Concentration (x)") +  
  theme_minimal()+
  scale_colour_manual(values=c("#B3AE36","#2D6480"))+
  theme(strip.text=element_text(face="bold"),
        legend.position = "none") 

plot_grid(p1, p2, labels=c("A", "B"), ncol=1, nrow=2, rel_heights = c(0.5, 0.5))
ggsave("figure 1.jpg", height=200, width=200, units="mm", 
       bg = "white", dpi = 300)
```

## Figure 2

```{r Figure weights, fig.cap="\\label{fig:plot_weights}DIC based model weight for the NEC3param model for each scenario as a function of the sample density (total.reps) and the number of experimental treatment levels (n.treatments)."}
#treat models as individuals keep them in their facets 

grob1 <- 
  dat %>% 
mutate(NEC3param=ifelse(grepl("Sig", scenarios), 1-NEC3param, NEC3param)) |> 
ggplot(aes(label, NEC3param, fill=n.treatments)) +
  geom_boxplot(aes(), position=position_dodge2(),outlier.shape=NA)+
  geom_point(alpha=0.25, pch=21,position = position_jitterdodge(), colour="black") +
  geom_hline(aes(yintercept=0.5))+
    theme_minimal() +

  coord_cartesian(clip = "off") +
  scale_y_continuous(name="Weight of underlying model", limits=c(NA, 1.1), breaks=c(0,0.25,0.5,0.75,1)) +
  scale_fill_manual(values=c("#B3AE36","#2D6480"))+
  labs(x="", fill="Treatments", tag="Treatments") +

  theme(axis.text.x = element_markdown(angle = 45, hjust=1, face="bold"),
        plot.tag.position=c(0.03, 0.925), 
        plot.tag=element_text(size=8)) +
       facet_wrap(~scenarios, nrow = 1, scales = "free_x")

grob2 <- 
  dat |> 
  mutate(NEC3param=ifelse(grepl("Sig", scenarios), 1-NEC3param, NEC3param)) |> 
  dplyr::select(total.reps, n, trials, n.treatments, scenarios, NEC3param) |> 
  group_by(total.reps, n.treatments, scenarios) |> 
  summarise(weight=round(median(NEC3param),3), .groups = "keep") |> 
  dplyr::mutate(Treatments = factor(n.treatments)) |> 
  ggplot(aes(total.reps, weight, colour = n.treatments)) +
  geom_line() + 
  geom_point() +
  scale_colour_manual(values=c("#B3AE36","#2D6480"))+
  labs(x="Total number of trials", colour="Treatments", 
       y ="Median weight") +
  facet_wrap(~scenarios, nrow = 1) +
  theme_minimal() +
  theme(axis.text.x = element_markdown(angle = 45, hjust=1, face="bold"),
        plot.tag.position=c(0.03, 0.925), 
        plot.tag=element_text(size=8))

plot_grid(grob1, grob2, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(0.6, 0.3))
ggsave("figure 2.jpg", height=200, width=200, units="mm", 
       bg = "white", dpi = 300)


```
## Figures 3

```{r plot-violin-medians, fig.height=5, fig.width=7, fig.cap="\\label{fig:plot_violin_medians}Median estimated model averaged endpoints estimates for each scenario for a well replicated (n.treatments=12, total.reps=2400) and poorly replicated experiment (n.treatments=8, total.reps=400). Shown as horizontal lines are the true endpoints for each scenario, including EC1, EC10, EC5 and NEC. Note that there is no theoretical NEC for the Sigmoidal scenarios."}
#Plot estimate distribution 

a1dat <- dat %>%
  mutate(NEC=est.NEC,
         NSEC=est.NSEC,
         `N(S)EC`=est.N.S.EC,
         EC10=est.EC10,
         EC05=est.EC05,
         EC01=est.EC01,
         total.reps=factor(total.reps)) %>%
  mutate(scenarios_f = as_factor(scenarios), 
        scenarios_f = fct_relevel(scenarios_f, "NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2")) %>% 
  dplyr::select(NEC, NSEC, `N(S)EC`, EC10, EC05, EC01, scenarios_f, n.treatments, label) %>%
  pivot_longer(cols = c("NEC", "NSEC", "N(S)EC", "EC10", "EC05", "EC01"), values_to="y", names_to="endpoint") %>%
  mutate(endpoint = as_factor(endpoint),
         endpoint = fct_relevel(endpoint, c("NEC", "NSEC", "N(S)EC", "EC10", "EC05", "EC01")))

a1out <- a1dat |> group_by(scenarios_f, n.treatments, label, endpoint) |> 
  summarise(estimate=median(y), .groups = "keep") |> 
  pivot_wider(names_from = scenarios_f, values_from = estimate)

a1 <- a1dat |>   ggplot(aes(x=endpoint, y=y, fill=n.treatments)) +
  geom_boxplot(aes(), outlier.shape=NA, 
               alpha=1, colour="black")+
  scale_fill_manual(values=c("#B3AE36","#2D6480"))+
  geom_hline(data = na.omit(true.vals.2), aes(yintercept = y, colour=endpoint)) +
  scale_colour_manual(values = c("#41b6c4", "#F08986", "#F02451", "#91003f")) +  
  labs(col="True endpoints", fill="Treatments") + 
  labs(x="", y="Estimated value") + 
  facet_grid(~scenarios_f, scales = "free_y") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=0.5))

a2dat <- dat %>%
  dplyr::select(n, n.treatments, total.reps, scenarios, trials, label,
         n.s.ec_ecx_vals, nsec_ecx_vals, ec1_ecx_vals, ec5_ecx_vals, ec10_ecx_vals, nec_ecx_vals)  %>%
  pivot_longer(cols=contains("ecx_vals"), names_to = "endpoint", values_to = "y") |> 
  dplyr::mutate(endpoint=toupper(gsub("_ecx_vals","", endpoint))) %>%
  dplyr::mutate(endpoint=gsub("N.S.", "N(S)", endpoint)) %>%
  dplyr::mutate(endpoint=ifelse(endpoint == "EC1", "EC01", endpoint)) %>%
  dplyr::mutate(endpoint=ifelse(endpoint == "EC5", "EC05", endpoint)) %>%
  dplyr::select(y, endpoint, n.treatments, total.reps, scenarios, label)  %>% 
  dplyr::mutate(
           scenarios_f = as_factor(scenarios), 
           scenarios_f = fct_relevel(scenarios_f, "NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2"),
           endpoint = as_factor(endpoint),
           endpoint = fct_relevel(endpoint, c("NEC", "NSEC", "N(S)EC", "EC10", "EC05", "EC01")))

a2out <- a2dat |> group_by(scenarios_f, n.treatments, label, endpoint) |> 
  summarise(effect=median(y), .groups = "keep") |> 
  pivot_wider(names_from = scenarios_f, values_from = effect)

a2 <- a2dat |> 
ggplot(aes(x=endpoint, y, fill=n.treatments)) +
  geom_boxplot(aes(), outlier.shape=NA, alpha=1, colour="black")+
  scale_fill_manual(values=c("#B3AE36","#2D6480"))+
  scale_y_continuous(limits=c(0, 30))+
  scale_x_discrete()+
  labs(x="", y="Actual effect size (%)", fill="Treatments", colour="True ECx") +
  geom_hline(data = true_ec_dat, aes(yintercept = y, colour=endpoint)) +
  scale_colour_manual(values = c("#F08986", "#F02451", "#91003f"))  +
  facet_grid(~scenarios_f, scales = "free_y") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=0.5))

precision_dat <- dat %>%
  mutate(NEC=est.NEC,
         NSEC=est.NSEC,
         `N(S)EC`=est.N.S.EC,
         EC10=est.EC10,
         EC05=est.EC05,
         EC01=est.EC01,
         total.reps=factor(total.reps)) %>%
  mutate(scenarios_f = as_factor(scenarios), 
        scenarios_f = fct_relevel(scenarios_f, "NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2")) %>% 
  dplyr::select(NEC, NSEC, `N(S)EC`, EC10, EC05, EC01, scenarios_f, n.treatments, total.reps) %>%
  pivot_longer(cols = c("NEC", "NSEC", "N(S)EC", "EC10", "EC05", "EC01"), values_to="y", names_to="endpoint") |> 
  mutate(
    endpoint = as_factor(endpoint),
    endpoint = fct_relevel(endpoint, c("NEC", "NSEC", "N(S)EC", "EC01", "EC05", "EC10")))
       
e1 <- precision_dat |> 
  group_by(total.reps, n.treatments, scenarios_f, endpoint) |> 
  dplyr::summarise(cv=(quantile(y, 0.75) - quantile(y, 0.25))/(quantile(y, 0.75)+quantile(y, 0.25)), 
                   .groups = "keep") |> 
  dplyr::mutate(Treatments = factor(n.treatments),
                total.reps=as.numeric(as.character(total.reps))) |> 
 ggplot(aes(total.reps, cv, colour = n.treatments)) +
  geom_line() + 
  geom_point() +
  scale_colour_manual(values=c("#B3AE36","#2D6480"))+
  labs(x="Total number of trials", colour="Treatments", 
       y ="Coefficient of variablity") +
  facet_grid(scenarios_f~endpoint, scales = "free_y") +
  theme_minimal() +
  theme(axis.text.x = element_markdown(angle = 45, hjust=1))

effects_dat <-  dat %>%
  dplyr::select(n, n.treatments, total.reps, scenarios, trials, label,
         n.s.ec_ecx_vals, nsec_ecx_vals, ec1_ecx_vals, ec5_ecx_vals, ec10_ecx_vals, nec_ecx_vals)  %>%
  pivot_longer(cols=contains("ecx_vals"), names_to = "endpoint", values_to = "estimate") |> 
  dplyr::mutate(endpoint=toupper(gsub("_ecx_vals","", endpoint))) %>%
  dplyr::mutate(endpoint=gsub("N.S.", "N(S)", endpoint)) %>%
  dplyr::mutate(endpoint=ifelse(endpoint == "EC1", "EC01", endpoint)) %>%
  dplyr::mutate(endpoint=ifelse(endpoint == "EC5", "EC05", endpoint)) %>%
  dplyr::select(estimate, endpoint, n.treatments, total.reps, scenarios, label)  %>% 
  dplyr::mutate(
           scenarios_f = as_factor(scenarios), 
           scenarios_f = fct_relevel(scenarios_f, "NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2"),
           endpoint = as_factor(endpoint),
           endpoint = fct_relevel(endpoint, c("NEC", "NSEC", "N(S)EC", "EC01", "EC05", "EC10"))) |> 
  left_join(true_all_dat) |> 
  mutate(diff=estimate-y)

e2 <- effects_dat |> 
  dplyr::select(total.reps, label, n.treatments, scenarios_f, endpoint, diff) |> 
  group_by(total.reps, n.treatments, scenarios_f, endpoint) |> 
  summarise(diff=median(diff), .groups = "keep") |> 
  dplyr::mutate(Treatments = factor(n.treatments)) |> 
 ggplot(aes(total.reps, diff, colour = n.treatments)) +
  geom_line() + 
  geom_point() +
  scale_colour_manual(values=c("#B3AE36","#2D6480"))+
  labs(x="Total number of trials", colour="Treatments", 
       y ="Median difference from expected") +
  facet_grid(scenarios_f~endpoint, scales = "free_y") +
  geom_hline(yintercept = 0, col="blue", lty=2) +
  theme_minimal() +
  theme(axis.text.x = element_markdown(angle = 45, hjust=1))

plot_grid(a1, e1, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(0.5, 0.5))

ggsave("figure 3.jpg", height=200, width=240, units="mm", 
       bg = "white", dpi = 300)

plot_grid(a2, e2, labels=c("A", "B"), ncol = 1, nrow = 2, rel_heights = c(0.5, 0.5))

ggsave("figure 4.jpg", height=200, width=240, units="mm", 
       bg = "white", dpi = 300)

vars <- c("NEC", "NSEC", "N(S)EC", "EC10", "EC05", "EC01")
vars <-c("NEC 1", "NEC 2", "Sigmoidal 1", "Sigmoidal 2")

cbind(a1out[, c("endpoint", "n.treatments", "label")], 
            signif(a1out[, vars], 3), 
            signif(a2out[, vars], 3)) |> 
  data.frame() |> 
  write.csv("Table S2.csv")

```
## Figure 5

```{r}
str(all_endpoint_dat)
str(all_fit_dat)

#back transform function 
back_fun<- function(x)(x^2)

#model weights 
cs_cu_weights <- read_csv("Table3.csv") %>% dplyr::select(Model, DIC, wi)

cu_wi_ord<- cs_cu_weights %>% arrange(desc(wi)) %>%  
  dplyr::select(Model) %>%  unique() %>% pull() 

cu_wi<- c("Averaged", cu_wi_ord)

cu_wi_top<- cs_cu_weights %>% arrange(desc(wi)) %>% slice(1:3) 
cu_lab1<- cs_cu_weights %>% arrange(desc(wi)) %>% #arrange by weights 
    mutate(Model= factor(Model, levels = cu_wi_ord)) %>% #reorder the levels based on weights
  filter(wi>0)#filter only the models with weight

cu_dat <- readxl::read_excel("case_study1_data.xlsx") %>% 
  rename(x=conc) %>% 
    mutate(y=pcon/100)#convert to proportion from percent


cu_mods<- data.frame(Model=c((cu_wi_top$Model), "Averaged"))
cu_dat_plus<- crossing(cu_dat, cu_mods) %>% 
  mutate(type = if_else(Model=="Averaged", "Averaged", 
                        if_else(startsWith(Model, "NEC"),"NEC","Sigmoidal"))) %>% 
    filter(Model %in% c(cu_lab1$Model) | Model == "Averaged")

#Estimates 
endpoints<- all_endpoint_dat %>% 
      rename(value="X50.", lw="X2.5.", up="X97.5.") %>% #rename median and interval values 
  mutate(value=as.double(value), lw=as.double(lw), up=as.double(up), #make values numeric
         Model = fct_recode(as.factor(Model),Averaged="averaged")) %>%  #capitalise averaged 
  mutate(across(where(is.double),~back_fun(.x))) %>% #back transformation

    filter(Model %in% c(cu_wi_top$Model) | Model == "Averaged") %>% #only select models with weight or the averaged model
  mutate(x=15, y=0.25, 
         label=str_c(estimate,": ", round(value,0), " (",round(lw,0),"-", round(up,0),")" ,sep=""))

#EC estimate of NSEC - case study 1
cu_x <- endpoints |> 
  dplyr::filter(Model=="Averaged") |> 
  dplyr::select(value) |> 
  unlist() |> 
  sqrt()
cu_xrange <- endpoints |> 
  dplyr::filter(Model=="Averaged") |> 
  dplyr::select(lw, up) |> 
  unlist() |> 
  sqrt()
ecx_nsec_cu <- estECX_manec(x=cu_x, X=norm_beta_2, x.range = cu_xrange)
ecx_nsec_cu

#labels for ECx values 
Cu_EC_labs<- Cu_EC_estimates %>% 
   mutate(estimate = if_else(Model=="Averaged", "Averaged", 
                        if_else(startsWith(Model, "NEC"),"NEC","Sigmoidal"))) %>% 

    filter(Model %in% c(cu_wi_top$Model) | Model == "Averaged") %>% 
    droplevels() %>% 
    mutate(label=str_c(ECx,": ", round(value,0), " (",round(lw,0),"-", round(up,0),")" ,sep=""),
           x=15,y=if_else(ECx== "EC1", 0.15,0.05))

Cu_EC10<- Cu_EC_labs %>% filter(ECx=="EC10")
Cu_EC1<- Cu_EC_labs %>% filter(ECx=="EC1")

#lines and ribbons 
  fit_dat<- all_fit_dat %>% 
         mutate(Model = fct_recode(as.factor(Model),Averaged="averaged")) %>% 
      mutate(x=back_fun(x)) %>% #back transformation
  left_join(cs_cu_weights %>%rename("Model"=1) ) %>% 
  mutate(Model= factor(Model, levels = cu_wi))%>% 
  filter(Model%in% cu_wi_top$Model | Model=="Averaged") %>% 
  mutate(type = if_else(Model=="Averaged", "Averaged", 
                        if_else(startsWith(as.character(Model), "NEC"),"NEC","Sigmoidal")))

   fig_cs1_labels<- data.frame(
    x=0, 
    y=1.20, 
    Model=c("Averaged", (cu_wi_top$Model)),     
    label=c("(A)", "(B)", "(C)", "(D)")) 


(fig_cs1<-ggplot(data=fit_dat)+
  geom_ribbon(data=fit_dat, aes(x=x, y=y,ymin=lw, ymax=up, fill=type),linetype=2, alpha=0.2, show.legend=FALSE)+
  geom_line(data=fit_dat, aes(x=x, y=y, colour=type), lwd=0.5)+
  geom_point(data=cu_dat_plus, aes(x=x, y=y, fill=type), pch=21, alpha=0.3)+
  geom_text(data=Cu_EC1, aes(label=label, x=x, y=y, colour=estimate), size=3, hjust=0,show.legend = FALSE)+
  geom_text(data=Cu_EC10, aes(label=label, x=x, y=y, colour=estimate), size=3, hjust=0,show.legend = FALSE)+

  scale_fill_manual(values=c("#704FC4","black"), name="Model")+
  scale_colour_manual(values=c("#704FC4","black"), name="Model")+
  
  new_scale_color()+
  new_scale_fill()+
  geom_rect(data=endpoints, aes(xmax=(up), xmin=(lw), ymin=-Inf, ymax=Inf, x=x, y=y, fill=estimate), alpha=0.2)+
  geom_text(data=endpoints, aes(label=label, x=x, y=y, colour=estimate), size=3, hjust=0,show.legend = FALSE)+
  geom_vline(data=endpoints, aes(xintercept=(value), colour=estimate),  lwd=0.8)+
    
  geom_text(data=fig_cs1_labels, aes(x=x,y=y, label=label), fontface="bold")+

  scale_colour_manual(values=c("#815BE3","black"), name="Estimate")+
  scale_fill_manual(values=c("#815BE3","black"), name="Estimate")+


  scale_x_continuous(trans="sqrt", labels = scales::label_number(accuracy=1), breaks=c(0.1,1,10,20, 50, 100))+
  scale_y_continuous(limits=c(0,1.4), breaks=c(0,0.20,0.40,0.60,0.80,1.00))+

  facet_wrap(~Model, ncol=2)+
  theme_minimal()+
  theme(axis.ticks = element_line(),
        panel.grid.minor = element_blank())+
  labs(x=expression("Concentration"~ (mu*g~{L^-1}~Cu)), y="Normalised response"))

ggsave("figure 5.jpg", height=180,width=200, units="mm", 
       bg = "white", dpi = 300)

# Estimate NOEC for table 3 
dunnett<- norm_beta_2$mod.fits$NEC3param$mod.dat %>% data.frame() %>% 
  mutate(cat=as.factor(signif(x, 1))) |> 
  group_by(cat) |> 
  mutate(mean.x=as.factor(back_fun(mean(x))))


fit.glmer<-glmmTMB(y~mean.x, family=brms::Beta(link = "logit", link_phi = "log"), data=dunnett)
summary(glht(fit.glmer, linfct=mcp(mean.x="Dunnett")))     

# Extract NEC for table 3
norm_beta_nec <- modify_jagsMANEC(norm_beta_2, 
                                model.set = ("NEC"))
norm_beta_nec2<- modify_jagsMANEC(norm_beta_nec, 
                                 drop.models = c("NECHormesis", "NECsigmoidal"))

norm_beta_nec2$NEC^2

```
## Figure 6

```{r figure cs2, fig.height=7, fig.width=7, fig.cap="\\label{fig:plot_CRs}Concentration response relationships.", warning=FALSE}

#convert transformed concentrations back to concentrations
cs_endpoints_2<- cs_endpoints %>% 
  mutate(med =xform1(as.numeric(`50%`)), 
         lw=xform1(as.numeric(`2.5%`)), 
         up=xform1(as.numeric(`97.5%`)),
         endpoint=fct_recode(endpoint, `N(S)EC`="NSEC")) 

cs_endpoints_2 |> 
  mutate(est=paste0(signif(med, 3), " (", signif(lw,3), "-", signif(up,3), ")", sep="")) |> 
  dplyr::select(sp, endpoint, est) |> 
  pivot_wider(names_from = endpoint, values_from = est) 


#shuffle any 0 or near 0 values up a little to plot on a log scale
cs_dat_2<- cs_dat %>% 
  mutate(x_num = xform1(x)) %>% 
  mutate(x_num=if_else(x_num<0.1, 0.1, x_num))

cs_predat_2<- cs_predat %>% 
  mutate(x_num=xform1(x)) %>% 
  mutate(x_num=if_else(x_num<0.1, 0.1, x_num)) %>% 
  mutate(fit=fct_recode(fit, "All" = "all"))


#text annotations

label_1 <- data.frame(label = c("NEC3param 0.95", "ECxWeibull2 0.41","ECxWeibull1 0.75","ECxWeibull2 0.59"),
                      sp = unique(cs_dat$sp), 
                       x=0.2, y=0.25)

label_2<- data.frame(label = c("ECxWeibull2 0.05", "NEC4param 0.38", "NEC3param 0.25", "ECxWeibull1 0.41"),
                      sp = unique(cs_dat$sp), 
                       x=0.2, y=0.15)
label_3<- data.frame(label = c( "", "ECxWeibull1 0.21",  "", "" ),
                      sp = unique(cs_dat$sp), 
                       x=0.2, y=0.05)

#plot facet labels
  
  fig_cs2_labels<- data.frame(
    x=0.05, 
    y=1.1, 
    sp= unique(cs_dat$sp), 
    label=c("(A)", "(B)", "(C)", "(D)")) 


(fig.cs2<-ggplot()+
  geom_ribbon(data=cs_predat_2, aes(x=x_num, y=y,ymin=lw, ymax=up, fill=fit),linetype=2, alpha=0.2)+
  geom_line(data=cs_predat_2, aes(x=x_num, y=y,colour=fit), lwd=0.5)+
  geom_point(data=cs_dat_2, aes(x=x_num, y=y),alpha=0.2)+
  geom_text(data=label_1, aes(x=x, y=y, label=label),size=3, hjust=0)+
  geom_text(data=label_2, aes(x=x, y=y, label=label),size=3, hjust=0)+
  geom_text(data=label_3, aes(x=x, y=y, label=label),size=3, hjust=0)+
  geom_text(data=fig_cs2_labels, aes(x=x, y=y, label=label), fontface="bold")+

  scale_colour_manual(values=c("#704FC4", "#16ABA5"), name="Model average \n group")+
  scale_fill_manual(values=c("#704FC4", "#16ABA5"), name="Model average \n group")+
  new_scale_color()+
  new_scale_fill()+
  geom_segment(data=cs_endpoints_2, aes(x=med, xend=med, y=0, yend=1, colour=endpoint, linetype=endpoint),lwd=0.8)+
  scale_colour_manual(values=c("#91003f","#41b6c4","#815BE3"), name="Estimate")+
  scale_x_log10(breaks=c(1, 10, 100, 1000, 10000))+
    scale_linetype_manual(values=c(3,2,1), name="Estimate")+
  facet_wrap(sp~., nrow=2)+
  theme_minimal()+
  theme(strip.text=element_text(face="bold.italic"),
        axis.ticks = element_line(),
        panel.grid.minor = element_blank())+
  labs(x=expression("Concentration"~ (mu*g~{L^-1}~TAH)), 
       y= "Normalised response",
       fill="Model group",colour="Model group"))

ggsave("figure 6.jpg", height=180,width=200, units="mm", 
       bg = "white", dpi = 300)


#EC1 case study 2
ec1_coral <- extract_ECx(Coral.out4.all, ECx.val = 1)
ec1_aa <- extract_ECx(out.aa.all, ECx.val = 1)
ec1_nd <- extract_ECx(out.nd.all, ECx.val = 1)
ec1_urchin <- extract_ECx(Urchin.out2, ECx.val = 1)
signif(xform1(ec1_coral),3)
signif(xform1(ec1_aa),3)
signif(xform1(ec1_nd),3)
signif(xform1(ec1_urchin),3)

#EC estimate of NSEC - case study 2
cs_endpoints
nsec_vals_cs <- cs_endpoints |> 
  data.frame() |>     
  dplyr::filter(endpoint=="NSEC") |> 
  tibble() |> 
  column_to_rownames("sp")  |> 
  dplyr::select(X50., X2.5., X97.5.) 

ec_nsec_coral <- estECX_manec(x=as.numeric(unlist(nsec_vals_cs["A. millepora", "X50."])), 
                              X=Coral.out4.all, 
                              x.range = as.numeric(unlist(nsec_vals_cs["A. millepora", c("X2.5.", "X97.5.")])))
ec_nsec_aa <- estECX_manec(x=as.numeric(unlist(nsec_vals_cs["A. amphitrite", "X50."])), 
                           X=out.aa.all, 
                           x.range = as.numeric(unlist(nsec_vals_cs["A. amphitrite", c("X2.5.", "X97.5.")])))
ec_nsec_nd <- estECX_manec(x=as.numeric(unlist(nsec_vals_cs["N. dorsatus", "X50."])), 
                           X=out.nd.all, 
                           x.range = as.numeric(unlist(nsec_vals_cs["N. dorsatus", c("X2.5.", "X97.5.")])))
ec_nsec_urchin <- estECX_manec(x=as.numeric(unlist(nsec_vals_cs["S. variolaris", "X50."])), 
                               X=Urchin.out2, 
                               x.range = as.numeric(unlist(nsec_vals_cs["S. variolaris", c("X2.5.", "X97.5.")])))
ec_nsec_coral
ec_nsec_aa
ec_nsec_nd
ec_nsec_urchin

# dunnets tests
## urchin
dat <- Urchin.out2$mod.fits$NEC3param$mod.dat |> 
  bind_cols() |> 
  mutate(suc=as.integer(round(N*y)),
         Tr=as.factor(xform1(x))) |> 
  data.frame()
fit.glmer<-glmmTMB(y~Tr, family=brms::Beta(link = "logit", link_phi = "log"), data=dat) 
summary(glht(fit.glmer, linfct=mcp(Tr="Dunnett")))     

## coral
dat <- Coral.out4.all$mod.fits$NEC3param$mod.dat |> 
  bind_cols() |> 
  mutate(suc=as.integer(round(N*y)),
         Tr=as.factor(xform1(x))) |> 
  data.frame()
fit.glmer<-glmmTMB(y~Tr, family=brms::Beta(link = "logit", link_phi = "log"), data=dat) 
summary(glht(fit.glmer, linfct=mcp(Tr="Dunnett")))     

## barnacle
dat <- out.aa.all$mod.fits$NEC3param$mod.dat |> 
  bind_cols() |> 
  mutate(suc=as.integer(round(N*y)),
         Tr=as.factor(xform1(x))) |> 
  data.frame()
fit.glmer<-glmmTMB(y~Tr, family=brms::Beta(link = "logit", link_phi = "log"), data=dat) 
summary(glht(fit.glmer, linfct=mcp(Tr="Dunnett")))   

## snail
dat <- out.nd.all$mod.fits$NEC3param$mod.dat |> 
  bind_cols() |> 
  mutate(suc=as.integer(round(N*y)),
         Tr=as.factor(xform1(x))) |> 
  data.frame()
fit.glmer<-glmmTMB(y~Tr, family=brms::Beta(link = "logit", link_phi = "log"), data=dat) 
summary(glht(fit.glmer, linfct=mcp(Tr="Dunnett")))   

```


```{r supp2}
all_mod_fits <- list(
  `Case study 1 _ C. armigera` = norm_beta_2$mod.fits,
  `Case study 2 _ A. amphitrite` = out.aa.all$mod.fits,
  `Case study 2 _ A. millepora` = Coral.out4.all$mod.fits,
  `Case study 2 _ N. dorsatus` = out.nd.all$mod.fits,
  `Case study 2 _ S. variolaris` = Urchin.out2$mod.fits  
)

all_params_out <- lapply(all_mod_fits, FUN = function(l){
  lapply(l, FUN = function(x){
      x$summary |> 
      data.frame()|> 
      rownames_to_column(var = "parameter") 
    }) |> 
    bind_rows(.id="model")  
}) |> 
  bind_rows(.id="species") |> 
  dplyr::filter(!grepl("SS", parameter)) |> 
  dplyr::filter(!grepl("deviance", parameter))

head(all_params_out)

write.csv(all_params_out, 
          file ="Supporting Information File 2.csv",
          row.names = FALSE)
```

