---
title: "Exploring alternative Bayesian estimates of low- and no-effect concentration thresholds"
author: "Rebecca Fisher"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: pdf_document
always_allow_html: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE)

require(jagsNEC)
require(tidyverse)
library(ggplot2)
library(ggthemes) 
library(ggnewscale)
library(kableExtra)
library(flextable)
library(officer)
library(ggtext)
library(ggh4x)
library(scales)

source('functions.R')

load(file="binomial_sim_results.RData")
load(file = "fitted_binom_examples.RData")

load("caste_study_results.RData")

x.range <- c(0.1, 10)
x.vec <- seq(x.range[1], x.range[2], length=50)

true.vals <- do.call("rbind", true.endpoints) %>%
  mutate(estimate=gsub("C1", "C01", endpoint),
         estimate=gsub("C5", "C05", endpoint),
         estimate=gsub("C010", "C10", endpoint))

dat <- all.sim.out %>%
  mutate(est.NEC=NEC_X50.,
         est.NSEC=NSEC01.ECxsigmoidal_X50.*ECxsigmoidal + NSEC01.NEC3param_X50.*NEC3param,
         est.EC10=ECx10.ECxsigmoidal_X50.*ECxsigmoidal + ECx10.NEC3param_X50.*NEC3param,
         est.EC05=ECx05.ECxsigmoidal_X50.*ECxsigmoidal + ECx05.NEC3param_X50.*NEC3param,
         est.EC01=ECx01.ECxsigmoidal_X50.*ECxsigmoidal + ECx01.NEC3param_X50.*NEC3param,
         est.NEC.up=NEC_X97.5.,
         est.NSEC.up=NSEC01.ECxsigmoidal_X97.5.*ECxsigmoidal + NSEC01.NEC3param_X97.5.*NEC3param,
         est.EC10.up=ECx10.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx10.NEC3param_X97.5.*NEC3param,
         est.EC05.up=ECx05.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx05.NEC3param_X97.5.*NEC3param,
         est.EC01.up=ECx01.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx01.NEC3param_X97.5.*NEC3param,     
         est.NEC.lw=NEC_X2.5.,
         est.NSEC.lw=NSEC01.ECxsigmoidal_X2.5.*ECxsigmoidal + NSEC01.NEC3param_X2.5.*NEC3param,
         est.EC10.lw=ECx10.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx10.NEC3param_X2.5.*NEC3param,
         est.EC05.lw=ECx05.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx05.NEC3param_X2.5.*NEC3param,
         est.EC01.lw=ECx01.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx01.NEC3param_X2.5.*NEC3param) 

labs_meta<- data.frame(total.reps=c(400,  600, 1200 , 800, 1600, 2400), 
           label = c("5 reps (10 trials)","5 reps (10 trials)","5 reps (20 trials)",
                     "5 reps (20 trials)", "10 reps (20 trials)","10 reps (20 trials)"))

all.sim.out.dat <- full_join(all.sim.out, labs_meta) %>% 
  mutate(label=as.factor(label), 
         label=fct_relevel(label, "5 reps (10 trials)","5 reps (20 trials)","10 reps (20 trials)"),
         scenarios_f = as_factor(scenarios), 
         scenarios_f = fct_relevel(scenarios_f, "NEC 1", "NEC 2" , "Sigmoidal 1", "Sigmoidal 2"))
  
coverage <- dat %>% 
  dplyr::mutate(
    # ac.NEC=ifelse(NEC>est.NEC.lw & NEC<est.NEC.up, 1, 0),
    # ac.EC10=ifelse(EC10>est.EC10.lw & EC10<est.EC10.up, 1, 0),
    # ac.EC05=ifelse(EC5>est.EC05.lw & EC5<est.EC05.up, 1, 0),
    # ac.EC01=ifelse(EC1>est.EC01.lw & EC1<est.EC01.up, 1, 0),
    # nsc.NEC=ifelse(NEC>est.NSEC.lw & NEC<est.NSEC.up, 1, 0),
    # nsc.EC10=ifelse(EC10>est.NSEC.lw, 1, 0)
    ## actual endpoints
    fn.NEC=ifelse(NEC<est.NEC.lw, 1, 0),
    fn.EC10=ifelse(EC10<est.EC10.lw, 1, 0),
    fn.EC05=ifelse(EC5<est.EC05.lw, 1, 0),
    fn.EC01=ifelse(EC1<est.EC01.lw, 1, 0),
    ns_fn.NEC=ifelse(NEC<est.NSEC.lw, 1, 0),
    ns_fn.EC10=ifelse(EC10<est.NSEC.lw, 1, 0),
    ns_fn.EC05=ifelse(EC5<est.NSEC.lw, 1, 0),
    ns_fn.EC01=ifelse(EC1<est.NSEC.lw, 1, 0),
    fp.NEC=ifelse(NEC>est.NEC.up, 1, 0),
    fp.EC10=ifelse(EC10>est.EC10.up, 1, 0),
    fp.EC05=ifelse(EC5>est.EC05.up, 1, 0),
    fp.EC01=ifelse(EC1>est.EC01.up, 1, 0),
    ns_fp.NEC=ifelse(NEC>est.NSEC.up, 1, 0),
    ns_fp.EC10=ifelse(EC10>est.NSEC.up, 1, 0),
    ns_fp.EC05=ifelse(EC5>est.NSEC.up, 1, 0),
    ns_fp.EC01=ifelse(EC1>est.NSEC.up, 1, 0),
    ## NSEC approximation
    nec_fp.EC10=ifelse(EC10>est.NEC.up, 1, 0),
    nec_fp.EC05=ifelse(EC5>est.NEC.up, 1, 0),
    nec_fp.EC01=ifelse(EC1>est.NEC.up, 1, 0),
    nec_fp.NEC=ifelse(NEC>est.NEC.up, 1, 0),
    ## NEC approximation
    nec_fn.EC10=ifelse(EC10<est.NEC.lw, 1, 0),
    nec_fn.EC05=ifelse(EC5<est.NEC.lw, 1, 0),
    nec_fn.EC01=ifelse(EC1<est.NEC.lw, 1, 0),
    nec_fn.NEC=ifelse(NEC<est.NEC.lw, 1, 0),    
    
  ) %>% 
  dplyr::select(key, 
                fp.NEC, fp.EC10, fp.EC05, fp.EC01, 
                ns_fp.NEC, ns_fp.EC10, ns_fp.EC05, ns_fp.EC01,
                fn.NEC, fn.EC10, fn.EC05, fn.EC01, 
                ns_fn.NEC, ns_fn.EC10, ns_fn.EC05, ns_fn.EC01,
                nec_fp.NEC, nec_fp.EC10,  nec_fp.EC05,  nec_fp.EC01,
                nec_fn.NEC, nec_fn.EC10, nec_fn.EC05, nec_fn.EC01, 
                total.reps) %>% 
  dplyr::group_by(key) %>% 
  dplyr::summarise_all(mean, .groups="keep", na.rm=TRUE) %>% 
  data.frame() %>% 
  left_join(scenario.dat)


```


## Figure 1 

Figure showing the models used to create the data for the simulation study. 

```{r plot-example, fig.height=5, fig.fullwidth=TRUE, fig.cap="\\label{fig:plot_scenarios}A sigmoidal concentration-response experiment showing estimation of NSEC. The solid black line shows the fitted Bayesian model. The horizontal red line is the lower 1 percentile of the lowest concentration treatment (the control). The blue lines show posterior predicted values of the response for each MCMC sample. NSEC for each MCMC sample is estimated as the intersection between the red and blues lines."}

fit.i <- fitted.binom$'12_5_0.9_10_Sigmoidal 1'$mod.fits$ECxsigmoidal
dat.i <- fit.i$mod.dat
y.i <- fit.i$pred.vals$y
post.i <- fit.i$pred.vals$posterior
x.i <- fit.i$pred.vals$x
lw.i <- quantile(post.i[1,], probs = 0.01)

plot(jitter(dat.i$x, factor=0.5), dat.i$y/dat.i$trials, pch=16, col=adjustcolor("black", alpha=0.25),
     xlab="Concentration", ylab="Response probability", bty="L")

abline(h=lw.i, col="red")
for(l in 1:50){
  lines(x.i, post.i[,l], col=adjustcolor("blue", alpha=0.1))
}
lines(x.i, y.i, lwd=1.25)

```


```{r ECxsigmoidal, include=TRUE, echo=TRUE}
ECxsigmoidal <- function(x, top, beta, d) {
  y.pred <- top * exp(-beta * (x)^d)
  
  return(y.pred)
}
```


```{r NEC3param, include=TRUE, echo=TRUE}
NEC3param <- function(x, NEC, top, beta) {
  pre.index <- which(x <= NEC)
  post.index <- which(x > NEC)
  x.seq.pre <- x[pre.index]
  x.seq.post <- x[post.index]
  
  y.pred <- rep(NA, length(x))
  
  y.pred.pre <- top
  y.pred.post <- top * exp(-beta * (x.seq.post - NEC))
  
  y.pred[pre.index] <- y.pred.pre
  y.pred[post.index] <- y.pred.post
  
  return(y.pred)
}
```


```{r plot-scenarios, fig.height=5, fig.fullwidth=TRUE, fig.cap="\\label{fig:plot_scenarios}Models used for each scenario in the simulation study"}
scenarios <- names(scenarios.list)
scenarios.dat <- do.call("rbind", scenarios.list) %>%
  data.frame() %>%
  rownames_to_column(var = "scenarios")

par(bty="n")
plot(x.vec, ECxsigmoidal(x=x.vec, top=0.9, beta=0.01, d=2), ylim = c(0,1), 
     pch=NA, ylab="Probability", xlab="Concentration")

lines(x.vec, do.call(ECxsigmoidal, c(list(x.vec), as.list(na.omit(scenarios.list$`Sigmoidal 1`)))), col=1)
lines(x.vec, do.call(ECxsigmoidal, c(list(x.vec), as.list(na.omit(scenarios.list$`Sigmoidal 2`)))), col=2)

lines(x.vec, do.call(NEC3param, c(list(x.vec), as.list(na.omit(scenarios.list$`NEC 1`)))), col=1, lty=2)
lines(x.vec, do.call(NEC3param, c(list(x.vec), as.list(na.omit(scenarios.list$`NEC 2`)))), col=2, lty=2)

legend("topright", legend=scenarios,
       lty=c(1,2,1,2,1,2), col=c(1,1,2,2,4,4), bty = "n")
```

## Figure 2


```{r Figure 2_plot weights, fig.cap="\\label{fig:plot_weights}DIC based model weight for the NEC3param model for each scenario as a function of the sample density (total.reps) and the number of experimental treatment levels (n.treatments)."}
#treat models as individuals keep them in their facets 

all.sim.out.dat  %>% 
 mutate(x.label = paste("<span style = 'color: ",
                         ifelse(all.sim.out.dat$n.treatments == 8, "#B3AE36", "#2D6480"),
                         ";'>",
                         label,
                         "</span>", sep = ""),
        x.label=as.factor(x.label),
        x.label=fct_relevel(x.label, 
                            "<span style = 'color: #B3AE36;'>5 reps (10 trials)</span>",
                            "<span style = 'color: #2D6480;'>5 reps (10 trials)</span>",
                            "<span style = 'color: #2D6480;'>5 reps (20 trials)</span>",
                            "<span style = 'color: #B3AE36;'>5 reps (20 trials)</span>",
                             "<span style = 'color: #B3AE36;'>10 reps (20 trials)</span>",
                            "<span style = 'color: #2D6480;'>10 reps (20 trials)</span>")) %>% 
ggplot(aes(x.label, NEC3param, fill=n.treatments)) +

  geom_boxplot(aes(), position=position_dodge2(),outlier.shape=NA)+
  geom_point(alpha=0.25, pch=21,position = position_jitterdodge(), colour="black") +
  geom_hline(aes(yintercept=0.5))+
    theme_minimal() +

  coord_cartesian(clip = "off") +
  scale_y_continuous(name="Weight of NEC model", limits=c(NA, 1.1), breaks=c(0,0.25,0.5,0.75,1)) +
  scale_fill_manual(values=c("#B3AE36","#2D6480"))+
  labs(x="", fill="Treatments", tag="Treatments:") +

  theme(axis.text.x = element_markdown(angle = 45, hjust=1, face="bold"),
        plot.tag.position=c(0.03, 0.925), 
        plot.tag=element_text(size=8))+
     ggh4x::facet_nested_wrap(~scenarios_f + n.treatments, nrow = 1,scales = "free_x")
   #facet_grid(~scenarios_f+n.treatments, scales="free",space = "free")

ggsave("ignore/figure 2.png", height=120, width=200, units="mm")

```

##Figure 3

```{r figure 3,  warning=FALSE}


fig.3.dat<- all.sim.out.dat %>%
  mutate(NSEC=NSEC01.ECxsigmoidal_X50.*ECxsigmoidal + NSEC01.NEC3param_X50.*NEC3param,
        NEC=NEC_X50.) %>%
  pivot_longer(cols=c("NSEC","NEC"), values_to = "y", names_to = "Value") %>% 
  select(y, n.treatments, total.reps, scenarios, Value, label)  %>% 
  mutate(Value=as_factor(Value),
         Value=fct_relevel(Value, "NSEC", "NEC"),
                 scenarios_f = as_factor(scenarios), 
        scenarios_f = fct_relevel(scenarios_f, "NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2")) %>% 
  #coloured x labels
   mutate(x.label = paste("<span style = 'color: ",
                         ifelse(all.sim.out.dat$n.treatments == 8, "#B3AE36", "#2D6480"),
                         ";'>",
                         label,
                         "</span>", sep = ""),
        x.label=as.factor(x.label),
        x.label=fct_relevel(x.label, 
                            "<span style = 'color: #B3AE36;'>5 reps (10 trials)</span>",
                            "<span style = 'color: #2D6480;'>5 reps (10 trials)</span>",
                            "<span style = 'color: #2D6480;'>5 reps (20 trials)</span>",
                            "<span style = 'color: #B3AE36;'>5 reps (20 trials)</span>",
                             "<span style = 'color: #B3AE36;'>10 reps (20 trials)</span>",
                            "<span style = 'color: #2D6480;'>10 reps (20 trials)</span>"))

true.vals.2<-true.vals %>% mutate(scenarios_f = as_factor(scenarios), 
          scenarios_f = fct_relevel(scenarios_f,"NEC 1", "NEC 2", "Sigmoidal 1" , "Sigmoidal 2"), 
          endpoint=fct_relevel(endpoint, "NEC", "EC1", "EC5", "EC10")) %>% 
    mutate(y_2 = if_else(str_detect(scenarios, "NEC")&endpoint %in% c("EC1", "EC5", "EC10"),  NA, y))

          
  fig_3_labels<- data.frame(
    x=1, 
    y=8.5, 
    label=c("(A)", "(B)", "(C)", "(D)", "(E)", "(F)", "(G)", "(H)"),
    scenarios_f=levels(fig.3.dat$scenarios_f),
    Value=c(rep("NSEC", 4), rep("NEC", 4))) %>% 
    mutate(Value=factor(Value, levels=c("NSEC", "NEC")))
  

(fig_3<-  fig.3.dat %>% 
ggplot(aes(label, y)) +
 #    geom_point(pch=21, alpha=0.2,  position = position_jitterdodge())+ 
  geom_boxplot(aes(fill=n.treatments), outlier.shape=NA, alpha=1, colour="black")+
  geom_hline(data = na.omit(true.vals.2), aes(yintercept = y, colour=endpoint), lwd=0.7) +  
  geom_text(data=fig_3_labels, aes(x=x,y=y, label=label), fontface="bold")+

  scale_fill_manual(values=c("#B3AE36","#2D6480"))+
  facet_grid(Value~scenarios_f) +
  scale_colour_manual(values = c("#41b6c4", "#df65b0", "#e7298a", "#91003f")) +
  

  theme_minimal() +
  scale_y_continuous(limits=c(NA, 8.5))+
  scale_x_discrete()+
  theme(axis.text.x = element_markdown(angle = 45, hjust=1, face="bold"),
        plot.margin = margin(10, 10, 10, 20),
        panel.spacing.y=unit(1, "lines")) +
  guides(fill = guide_legend(override.aes = list(alpha=1)),
                 colour = guide_legend(override.aes = list(alpha=1))) +  
  labs(x="", 
       y="Estimated value",
       fill="Treatments",
       colour="Estimate"))
 
 ggsave("ignore/figure 3.png", height=160, width=240, units="mm")
```
##Figure 4 

Case study demonstrating model averaging

```{r}
 load("cu_pred_vals.RData")

str(all_endpoint_dat)
str(all_fit_dat)


#back transform function 
back_fun<- function(x)(exp(x)-1)
#model weights 
cs_cu_weights <- read_csv("cs_cu_weights.csv")

cu_wi_ord<- cs_cu_weights %>% arrange(desc(wi)) %>% rename("Model"=1) %>%  
  select(Model) %>%  unique() %>% pull() 

cu_wi<- c("Averaged", cu_wi_ord)

cu_wi_top<- cs_cu_weights %>% arrange(desc(wi)) %>% slice(1:3) %>% rename("Model"=1)
cu_lab1<- cs_cu_weights %>% arrange(desc(wi)) %>% rename("Model"=1)%>% #arrange by weights / rename fist column to model
    mutate(Model= factor(Model, levels = cu_wi_ord)) %>% #reorder the levels based on weights
  filter(wi>0)#filter only the models with weight

#cu data

cu_dat <- read.csv("C. armigera combined.csv") %>% 
  dplyr::filter(Metal == "Cu") %>% 
  dplyr::mutate(log.x = log(Conc + 1), 
                x=if_else(Conc<0.1, 0.1, Conc)) %>% 
    rename(y=Pcon)

cu_dat_2<- rbind(
  cu_dat %>% mutate(type="All"), 
  cu_dat %>% mutate(type="Single")
)

cu_mods<- data.frame(Model=c(levels(cu_lab1$Model), "Averaged"))
cu_dat_plus<- crossing(cu_dat, cu_mods) %>% 
  mutate(type = if_else(Model=="Averaged", "Averaged", 
                        if_else(startsWith(Model, "NEC"),"NEC","Sigmoidal"))) %>% 
    filter(Model %in% c(cu_lab1$Model) | Model == "Averaged")

#Estimates 

endpoints<- all_endpoint_dat %>% 
      rename(value="X50.", lw="X2.5.", up="X97.5.") %>% #rename median and interval values 
  mutate(value=as.double(value), lw=as.double(lw), up=as.double(up), #make values numeric
         Model = fct_recode(as.factor(Model),Averaged="averaged")) %>%  #capitalise averaged 
  mutate(across(where(is.double),~back_fun(.x))) %>% #back transformation

    filter(Model %in% c(cu_lab1$Model) | Model == "Averaged") %>% #only select models with weight or the averaged model
  mutate(x=0.05, y=if_else(estimate=="NSEC"|estimate=="N(S)EC", 15, #add values for geom_text position on plots
                   if_else(estimate=="NEC", 5,25)),
          label=str_c(estimate," ", round(value,0), " (",round(lw,0),"-", round(up,0),")" ,sep=""))



#lines and ribbons 

  fit_dat<- all_fit_dat %>% 
     mutate(Model = fct_recode(as.factor(Model),Averaged="averaged")) %>% 
  left_join(cs_cu_weights %>%rename("Model"=1) ) %>% 
  mutate(Model= factor(Model, levels = cu_wi))%>% 
  filter(wi>0 | Model=="Averaged") %>% 
  mutate(type = if_else(Model=="Averaged", "Averaged", 
                        if_else(startsWith(as.character(Model), "NEC"),"NEC","Sigmoidal")))
  
  fig_4_labels<- data.frame(
    x=0.05, 
    y=120, 
    Model=levels(fit_dat$Model), 
    label=c("(A)", "(B)", "(C)", "(D)")) %>% 
    filter(Model%in%fit_dat$Model)
  
  #to do: 
#separate averaged - recombine in single graph
#fix factor relevel not passing to facet 


(fig_4<-ggplot(data=fit_dat)+
  geom_ribbon(data=fit_dat, aes(x=back_fun(x), y=y,ymin=lw, ymax=up, fill=type), alpha=0.3, show.legend=FALSE)+
  geom_line(data=fit_dat, aes(x=back_fun(x), y=y, colour=type, show.legend=FALSE))+
  geom_point(data=cu_dat_plus, aes(x=x, y=y, fill=type),pch=21, alpha=0.3, show.legend=FALSE)+
 
  scale_fill_manual(values=c("#704FC4","#16ABA5","black"), name="Model")+
  scale_colour_manual(values=c("#704FC4","#16ABA5","black"), name="Model")+
  
  new_scale_color()+
  new_scale_fill()+
 
  geom_rect(data=endpoints, aes(xmax=(up), xmin=(lw), ymin=-Inf, ymax=Inf, x=x, y=y, fill=estimate), alpha=0.2)+
  geom_text(data=endpoints, aes(label=label, x=x, y=y, colour=estimate), size=3, hjust=0,show.legend = FALSE)+
  geom_vline(data=endpoints, aes(xintercept=(value), colour=estimate),  lwd=1)+
    
  geom_text(data=fig_4_labels, aes(x=x,y=y, label=label), fontface="bold")+

  scale_colour_manual(values=c("#815BE3","#41b6c4","black"), name="Estimate")+
  scale_fill_manual(values=c("#815BE3","#41b6c4","black"), name="Estimate")+


  scale_x_log10(labels = scales::label_number(accuracy=1), breaks=c(0.1,1,10,100))+
  scale_y_continuous(limits=c(0,140), breaks=c(0,20,40,60,80,100))+

  facet_wrap(~Model, ncol=2)+
  theme_minimal()+
  labs(x=expression("Copper concentration"~ (mu*g~{L^-1}~Cu)), y="Normalised response"))



ggsave("ignore/figure 4.png", height=180,width=200, units="mm")

```



##Figure 5

Case study using data from a study that investigated the the effects of 40% weathered Ichthys condensate WAF on four tropical marine species. 


```{r figure 5, fig.height=7, fig.width=7, fig.cap="\\label{fig:plot_CRs}Concentration response relationships.", warning=FALSE}
load("Case_study_condensate_for_plotting.RData")

#convert transformed concentrations back to concentrations
cs_endpoints_2<- cs_endpoints %>% 
  mutate(med =xform1(as.numeric(`50%`)), 
         lw=xform1(as.numeric(`2.5%`)), 
         up=xform1(as.numeric(`97.5%`)),
         endpoint=fct_recode(endpoint, `N(S)EC`="NSEC")) 

#shuffle any 0 or near 0 values up a little to plot on a log scale
cs_dat_2<- cs_dat %>% 
  mutate(x_num = xform1(x)) %>% 
  mutate(x_num=if_else(x_num<0.1, 0.1, x_num))

cs_predat_2<- cs_predat %>% 
  mutate(x_num=xform1(x)) %>% 
  mutate(x_num=if_else(x_num<0.1, 0.1, x_num)) %>% 
  mutate(fit=fct_recode(fit, "Averaged" = "all"))


#text annotations

label_1 <- data.frame(label = c("NEC3param 0.95", "ECxWeibull2 0.41","ECxWeibull1 0.75","ECxWeibull2 0.59"),
                      sp = unique(cs_dat$sp), 
                       x=1, y=0.25)

label_2<- data.frame(label = c("ECxWeibull2 0.05", "NEC4param 0.38", "NEC3param 0.25", "ECxWeibull1 0.41"),
                      sp = unique(cs_dat$sp), 
                       x=1, y=0.15)
label_3<- data.frame(label = c( "", "ECxWeibull1 0.21",  "", "" ),
                      sp = unique(cs_dat$sp), 
                       x=1, y=0.05)

#plot facet labels
  
  fig_5_labels<- data.frame(
    x=0.05, 
    y=1.1, 
    sp= unique(cs_dat$sp), 
    label=c("(A)", "(B)", "(C)", "(D)")) 


(fig.5<-ggplot()+
  geom_ribbon(data=cs_predat_2, aes(x=x_num, y=y,ymin=lw, ymax=up, fill=fit), alpha=0.3)+
  geom_line(data=cs_predat_2, aes(x=x_num, y=y,colour=fit), lwd=1)+
  geom_point(data=cs_dat_2, aes(x=x_num, y=y),alpha=0.3)+
  geom_text(data=label_1, aes(x=x, y=y, label=label),size=3)+
  geom_text(data=label_2, aes(x=x, y=y, label=label),size=3)+
  geom_text(data=label_3, aes(x=x, y=y, label=label),size=3)+
  geom_text(data=fig_5_labels, aes(x=x, y=y, label=label), fontface="bold")+

  scale_colour_manual(values=c("#704FC4", "#16ABA5"), name="Model average \n group")+
  scale_fill_manual(values=c("#704FC4", "#16ABA5"), name="Model average \n group")+
  new_scale_color()+
  new_scale_fill()+
  geom_segment(data=cs_endpoints_2, aes(x=med, xend=med, y=0, yend=1, colour=endpoint),lwd=1)+
  scale_colour_manual(values=c("#91003f","#41b6c4","#815BE3"), name="Estimate")+
  scale_x_log10(breaks=c(1, 10, 100, 1000, 10000))+
  facet_wrap(sp~., nrow=2)+
  theme_minimal()+
  theme(strip.text=element_text(face="bold.italic"))+
  labs(x=expression("Concentration"~ (mu*g~{L^-1}~TAH)), 
       y= "Normalised response",
       fill="Model group",colour="Model group"))


ggsave("ignore/figure 5.png", height=180, width=200,units="mm" )

```





## Bonus plots 


```{r NSEC NEC comparison figure, fig.cap="\\label{fig:plot_4}Median estimated model averaged NSEC values based on a 99% certainty value for each scenario as a function of estimated NEC from the same data. Shown as horizontal and vertical lines are the true toxicity estimates for each scenario, including EC1, EC10, EC5 and NEC. Note that there is no theoretical NEC for the sigmoidal scenarios, although an ‘NEC’ estimate was obtained using the NEC model. The diagonal black line shows the 1:1 relationship indicating where NSEC estimates are equal to estimated NEC. Points are coloured according to the total sample size (total.reps, number of replicates x number of individuals).", warning=FALSE}

cols <- colorRampPalette(c("purple","darkgrey","black"))(length(unique(all.sim.out$total.reps)))
total.reps.levels <- as.character(sort(unique(all.sim.out$total.reps)))
tot_colour_ramp = c("#D4CF3F","#4AA6D4", "#B3AE36","#2D6480", "#6E6B21", "#1D4254")

true.vals<- true.vals %>% mutate(endpoint=fct_relevel(endpoint, "NEC", "EC1", "EC5", "EC10"))
plotdat.all.sim.out<- all.sim.out %>%
 mutate(NEC=NEC_X50.,
NSEC=NSEC01.ECxsigmoidal_X50.*ECxsigmoidal + NSEC01.NEC3param_X50.*NEC3param,
EC10=ECx10.ECxsigmoidal_X50.*ECxsigmoidal + ECx10.NEC3param_X50.*NEC3param,
EC05=ECx05.ECxsigmoidal_X50.*ECxsigmoidal + ECx05.NEC3param_X50.*NEC3param,
EC01=ECx01.ECxsigmoidal_X50.*ECxsigmoidal + ECx01.NEC3param_X50.*NEC3param) %>%
select(NEC, NSEC, EC10, EC05, EC01, scenarios, n.treatments, total.reps) %>%
#mutate(total.reps=as.factor(total.reps)) %>% 
na.omit()

plotdat.all.sim.out.t8<- plotdat.all.sim.out %>% filter(n.treatments==8) %>% 
  mutate(reps= as.factor(total.reps), 
         reps=fct_recode(reps,
                          "5 reps (10 trials)" = "400",
                          "5 reps (20 trials)"="800",
                          "10 reps (20 trials)" ="1600", 
                         ))
plotdat.all.sim.out.t12<- plotdat.all.sim.out %>% filter(n.treatments==12) %>% 
  mutate(reps= as.factor(total.reps), 
         reps=fct_recode(reps,
                          "5 reps (10 trials)" = "600",
                          "5 reps (20 trials)"="1200",
                          "10 reps (20 trials)" ="2400", 
                         ))

ggplot(plotdat.all.sim.out.t8) +
geom_point( aes(NEC, NSEC,fill=reps), alpha=0.3, pch=21) +
scale_fill_manual(values=c("#D4CF3F", "#B3AE36", "#6E6B21"), name="8 treatments")+
guides(fill = guide_legend(override.aes = list(alpha=1))) +  

  new_scale_fill() +
geom_point(data=plotdat.all.sim.out.t12, aes(NEC, NSEC,fill=reps), alpha=0.3, pch=21) +
scale_fill_manual(values=c("#4AA6D4","#2D6480","#1D4254"), name="12 treatments")+
geom_segment(data = na.omit(true.vals), aes(x=0, y=y, xend=y, yend = y, colour=endpoint), lwd=0.5)+
geom_segment(data = na.omit(true.vals), aes(x=y, y=0, xend=y, yend = y, colour=endpoint), lwd=0.5)+
geom_abline(aes(intercept = 0, slope = 1, linetype = "dashed"), show.legend = FALSE, lwd=0.5) +
labs(x="Estimated NEC", y="Estimated NSEC")+


scale_colour_manual(values = c("#41b6c4", "#df65b0", "#e7298a", "#91003f" ), name="Estimate") +
guides(colour = guide_legend(order = 1))+
facet_wrap(~scenarios, scales="free") +
  guides(fill = guide_legend(override.aes = list(alpha=1))) +  

theme_minimal() +
theme(axis.text.x = element_text(angle = 45, hjust=1))

```


```{r plot-violin-medians, fig.height=5, fig.width=7, fig.cap="\\label{fig:plot_violin_medians}Median estimated model averaged endpoints estimates for each scenario for a well replicated (n.treatments=12, total.reps=2400) and poorly replicated experiment (n.treatments=8, total.reps=400). Shown as horizontal lines are the true endpoints for each scenario, including EC1, EC10, EC5 and NEC. Note that there is no theoretical NEC for the Sigmoidal scenarios."}
#Plot estimate distribution 

all.sim.out %>%
  mutate(NEC=NEC_X50.,
         NSEC=NSEC01.ECxsigmoidal_X50.*ECxsigmoidal + NSEC01.NEC3param_X50.*NEC3param,
         EC10=ECx10.ECxsigmoidal_X50.*ECxsigmoidal + ECx10.NEC3param_X50.*NEC3param,
         EC05=ECx05.ECxsigmoidal_X50.*ECxsigmoidal + ECx05.NEC3param_X50.*NEC3param,
         EC01=ECx01.ECxsigmoidal_X50.*ECxsigmoidal + ECx01.NEC3param_X50.*NEC3param,
         total.reps=factor(total.reps)) %>%
  filter(total.reps=="2400" | total.reps=="400") %>%
  select(NEC, NSEC, EC10, EC05, EC01, scenarios, n.treatments, total.reps) %>%
  mutate(fact=paste(scenarios, total.reps)) %>%
  pivot_longer(cols = c("NEC", "NSEC", "EC10", "EC05", "EC01"), values_to="y", names_to="endpoint") %>%
  ggplot(aes(x=endpoint, y=y, fill=total.reps)) +#, col=endpoint)) +
  #labs(col="Estimated endpoints") + 
  #geom_violin(position=position_dodge(1)) +
  geom_split_violin(col="black", alpha=0.7) +
  scale_fill_colorblind() +
  new_scale_colour() +
  geom_hline(data = na.omit(true.vals.2), aes(yintercept = y, colour=endpoint)) +
  scale_colour_manual(values = c("#41b6c4", "#df65b0", "#e7298a", "#91003f" )) +  
  labs(col="True endpoints") + 
  ylab("Estimated value") + 
  facet_wrap(~scenarios, scales="free", nrow = 1) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))
```

```{r plot-cbands, fig.height=5, fig.width=7, fig.cap="\\label{fig:plot_cbands}Estimated 95% confidence band range for model averaged endpoints estimates for each scenario for a well replicated (n.treatments=12, total.reps=2400) and poorly replicated experiment (n.treatments=8, total.reps=400)"}
#Plot of confidence bands of the estimates
all.sim.out %>%
  mutate(NEC.lw=NEC_X2.5.,
         NSEC.lw=NSEC01.ECxsigmoidal_X2.5.*ECxsigmoidal + NSEC01.NEC3param_X2.5.*NEC3param,
         EC10.lw=ECx10.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx10.NEC3param_X2.5.*NEC3param,
         EC5.lw=ECx05.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx05.NEC3param_X2.5.*NEC3param,
         EC1.lw=ECx01.ECxsigmoidal_X2.5.*ECxsigmoidal + ECx01.NEC3param_X2.5.*NEC3param,
         NEC.up=NEC_X97.5.,
         NSEC.up=NSEC01.ECxsigmoidal_X97.5.*ECxsigmoidal + NSEC01.NEC3param_X97.5.*NEC3param,
         EC10.up=ECx10.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx10.NEC3param_X97.5.*NEC3param,
         EC5.up=ECx05.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx05.NEC3param_X97.5.*NEC3param,
         EC1.up=ECx01.ECxsigmoidal_X97.5.*ECxsigmoidal + ECx01.NEC3param_X97.5.*NEC3param,
         NEC=NEC.up-NEC.lw,
         NSEC=NSEC.up-NSEC.lw,
         EC10=EC10.up-EC10.lw,
         EC05=EC5.up-EC5.lw,
         EC01=EC1.up-EC1.lw,         
         total.reps=factor(total.reps)) %>%
  filter(total.reps=="2400" | total.reps=="400") %>%
  select(NEC, NSEC, EC10, EC05, EC01, scenarios, n.treatments, total.reps) %>%
  pivot_longer(cols = c("NEC", "NSEC", "EC10", "EC05", "EC01"), values_to="y", names_to="endpoint") %>%
  ggplot(aes(endpoint, y, fill=n.treatments))+
  geom_split_violin(col="black", alpha=0.7) +
  scale_fill_manual(values=c("#B3AE36","#2D6480"))+
  labs(y="Estimated value", fill="Treatments") + 
  coord_cartesian(ylim=c(0,2))+
  facet_wrap(~scenarios, nrow=2) +
  scale_colour_manual(values = c("#41b6c4", "#df65b0", "#e7298a", "#91003f")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))


```


```{r plot-exceedance, fig.height=7, fig.width=7, fig.cap="\\label{fig:plot_coverage}Exceedance rates from 100 simulations as a function of the total number of simulated replicates (total.reps). Shown are exceedance rates for the actual endpoint estimates, including EC1, EC10, EC5 and NEC; as well as the estimate based on NSEC for those same endpoints. The dashed horizontal line indicates the expected 0.025 probability, assuming errors are equal at each end of the credible interval. Note that there is no theoretical NEC for the Sigmoidal scenarios.", warning=FALSE}
coverage %>% 
  pivot_longer(cols=c("fp.NEC", "fp.EC10", "fp.EC05", "fp.EC01", 
                      "ns_fp.NEC", "ns_fp.EC10",  "ns_fp.EC05", "ns_fp.EC01",
                      "fn.NEC", "fn.EC10", "fn.EC05", "fn.EC01", 
                      "ns_fn.NEC", "ns_fn.EC10",  "ns_fn.EC05",  "ns_fn.EC01",
                      "nec_fn.NEC", "nec_fn.EC10",  "nec_fn.EC05",  "nec_fn.EC01",
                      "nec_fp.NEC", "nec_fp.EC10",  "nec_fp.EC05",  "nec_fp.EC01"),
               names_to = "endpoint", values_to = "coverage") %>% 
  dplyr::mutate(type=ifelse(grepl("ns_", endpoint), 
                            "NSEC", ifelse(grepl("nec_", endpoint), "NEC", "Actual")),
                error=ifelse(grepl("fp.", endpoint), 
                            "(FP/1)", "(FN/2)")) %>%
  unite(col = "type", type, error, sep = " ") %>% 
  dplyr::mutate(endpoint=gsub("nec_", "", gsub("ns_", "", gsub("fn.", "", 
                              gsub("fp.", "", endpoint))))) %>% 
  ggplot(aes(x=total.reps, y=coverage, colour=endpoint)) +
  geom_point(position = position_jitter()) +
  geom_abline(slope=0, intercept=0.025, lty=2) +
  ylab("Exceedance rate") +
  xlab("Total number of trials in binomial experiment") +
  facet_grid(rows=vars(scenarios), cols=vars(type), scales = "fixed") +
  scale_colour_manual(values = c("orange", "cyan", "blue", "red")) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust=1))

```

